apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-deployment.yml
  - backend-service.yml
  - frontend-deployment.yml
  - frontend-service.yml
  - database-deployment.yml
  - database-service.yml

labels:
  - pairs:
      app.kubernetes.io/name: qa-lab
      app.kubernetes.io/managed-by: kustomize
